name: cpedidos_pmp
description: Controle de Pedidos da Prefeitura Municipal de Penápolis.
publish_to: 'none'
version: 1.2.1+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.6
  firebase_database: ^10.0.9
  mask: ^1.0.4
  email_validator: ^2.1.17
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  lottie: ^2.2.0
  flutter_svg: ^2.0.1
  result_dart: ^1.0.5
  sentry_flutter: ^6.20.1
  pdf: ^3.9.0
  printing: ^5.10.1
  flutter_modular: ^5.0.3
  js: ^0.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.1
  plugin_platform_interface: ^2.0.0
  modular_test: ^2.0.0
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/fonts/
