name: cpedidos_pmp
description: Controle de Pedidos da Prefeitura Municipal de Penápolis.
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.6
  firebase_database: ^10.0.14
  cloud_firestore: ^4.4.3
  mask: ^1.0.4
  email_validator: ^2.1.17
  lottie: ^2.2.0
  flutter_svg: ^2.0.1
  result_dart: ^1.0.5
  sentry_flutter: ^6.20.1
  go_router: ^6.2.0
  auto_injector: ^1.0.2+2
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4
  shared_preferences: ^2.0.18
  universal_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutterando_analysis: ^0.0.2
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/catalog/
