name: cpedidos_pmp
description: Controle de Pedidos da Prefeitura Municipal de Penápolis.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.6
  firebase_database: ^10.0.9
  flutter_mobx: ^2.0.6+5
  mask: ^1.0.4
  asuka: ^2.0.1+3
  email_validator: ^2.1.17
  kiwi: ^4.0.3
  go_router: ^6.0.6
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  lottie: ^2.2.0
  universal_io: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
