name: CI
on:
  pull_request:
    branches: [main]

jobs:
  flutter-tests:
    name: Flutter Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Flutter Version
        run: flutter --version

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Run Analyzer
        run: flutter analyze

      - name: Run Unit and Widget Tests
        run: flutter test

      - name: Test Build Web App
        run: flutter build web --release